# Generated by Django 5.2 on 2025-05-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('app_name', models.CharField(max_length=100)),
                ('actions', models.CharField(max_length=100)),
            ],
        ),
    ]
