# Generated by Django 5.2 on 2025-05-05 07:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('organisation_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('industry_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '1. Organizations',
                'permissions': [('can_read_organization', 'Can read organization'), ('can_create_organization', 'Can create organization'), ('can_update_organization', 'Can update organization'), ('can_delete_organization', 'Can delete organization')],
            },
        ),
    ]
