# Generated by Django 5.2 on 2025-05-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
            ],
            options={
                'permissions': [('can_read_book', 'Can read book'), ('can_create_book', 'Can create book'), ('can_update_book', 'Can update book'), ('can_delete_book', 'Can delete book')],
            },
        ),
    ]
