# Generated by Django 5.2 on 2025-05-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('can_read_article', 'Can read article'), ('can_create_article', 'Can create article'), ('can_update_article', 'Can update article'), ('can_delete_article', 'Can delete article')]},
        ),
    ]
